<?xml version="1.0" encoding="utf-8"?><Database Name="AddressBook" Class="Contact_managerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-G06U76V;Initial Catalog=AddressBook;Integrated Security=True" SettingsObjectName="contact_linq_manager.Properties.Settings" SettingsPropertyName="AddressBookConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Addressbook" Member="Addressbooks">
    <Type Name="Addressbook">
      <Column Name="PKAddressId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FKStateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FKUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="State_Addressbook" Member="State" ThisKey="FKStateId" OtherKey="PKStateId" Type="State" IsForeignKey="true" />
      <Association Name="UserDetail_Addressbook" Member="UserDetail" ThisKey="FKUserId" OtherKey="PKUserId" Type="UserDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="PKCountryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ZipCodeStart" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ZipCodeEnd" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Country_State" Member="States" ThisKey="PKCountryId" OtherKey="FKCountryId" Type="State" />
    </Type>
  </Table>
  <Table Name="dbo.State" Member="States">
    <Type Name="State">
      <Column Name="PKStateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FKCountryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="State_Addressbook" Member="Addressbooks" ThisKey="PKStateId" OtherKey="FKStateId" Type="Addressbook" />
      <Association Name="Country_State" Member="Country" ThisKey="FKCountryId" OtherKey="PKCountryId" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserDetails" Member="UserDetails">
    <Type Name="UserDetail">
      <Column Name="PKUserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmailId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="UserDetail_Addressbook" Member="Addressbooks" ThisKey="PKUserId" OtherKey="FKUserId" Type="Addressbook" />
    </Type>
  </Table>
</Database>